pipeline {
    
	agent any 
	parameters{
     string(defaultValue: "test_pod",description: "Please type the name of your deployment.",name: "deployName")
	 choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"],
     description: "Please select the AZ to deploy this service.",name: "deployAZ")
	 booleanParam(defaultValue: true,description: "Do you wish to deploy the service?",name: "myBoolean")
	 
	 }

	stages {
	  stage ("user input") {
	  
	    steps {
		  
		  echo " Deployment name is ${params.deployName}." 
		}
	  }
	  
	  stage ("Environment selection") {
	    steps {
	      echo " ${params.deployName} will get deployed to ${params.deployAZ}" 
	  }
	}
	
	  stage("Ok to proceed"){
	     steps{
		   echo "Do you wish to proceed ${params.myBoolean}?"
		 }
	  }
	}
}